### ISSUE TITLE
Ktor 2.0.3 - KGraphql not parse errors

### ISSUE THREAD

**Issue by Francynox** [ESchouten/CleanArchitecture#19]
I noticed that with Ktor 2.0.3 when a query or a mutation trows an error the Graphql server shows the error like this

(example with login query)
`{
  "error": "Server response was missing for query 'Login'."
}`

in Ktor 2.0.1 errors are shown instead like this
`{
  "errors": [
    {
      "message": "Invalid authentication",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": []
    }
  ]
}`

is this new behaviour correct or stills a parsing error with this new Ktor version?

ps: also tried with the new version of KGrapgql 0.17.15

**Comment by ESchouten** [comment]
Fix in main!
Thank you for the heads-up! @Francynox  👍🏻
