### ISSUE TITLE
No licence

### ISSUE THREAD

**Issue by zypus** [ESchouten/CleanArchitecture#9]
I assume the repo is meant as an example, especially as it is linked here [https://kgraphql.io/Examples/](https://kgraphql.io/Examples/). However as long as there is no appropriate licence attached to it, nobody is actually allowed to use this as a starting point for their own project. See [https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license) for details.

If this isn't intentional, would you mind adding a licence file?

**Comment by ESchouten** [comment]
Good point! What would be best fitting? MIT?
